const menus = [
  {
    id: 101,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ JARDINERA",
    postre: "NARANJA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },

  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ JARDINERA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA C/ENSALADA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO C/ ENSALADA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUST. C/PURE MIXTO",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ARROZ PRIMAVERA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "BANANA",
    regimen: "general",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "ALBONDIGAS CON SALSA Y PURE PURE DE PAPA Y BATATA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "MANDARINA",
    regimen: "general",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "NARANJA",
    regimen: "general",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "NARANJA",
    regimen: "general",
  },

  {
    id: 201,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ SALSA Y ENSALADA JARDINERA",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "AZUCAR BLANCA", pb: 0.003, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "HARINA DE TRIGO 000", pb: 0.16, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "LEVADURA SECA", pb: 0.003, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO MOZZARELLA", pb: 0.18, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON SALSA CRIOLLA Y PAPAS AL NATURAL",
    postre: "GELATINA",
    regimen: "oficiales",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "MILANESA CASERA CON ENSALADA",
    postre: "FLAN DE VAINILLA",
    regimen: "oficiales",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "ALBONDIGAS CON FIDEOS",
    postre: "NARANJA",
    regimen: "oficiales",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "oficiales",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON VERDURAS EN JULIANA",
    postre: "FLAN",
    regimen: "oficiales",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "RAVIOLES DE VERDURA CON ESTOFADO",
    postre: "FLAN DE VAINILLA",
    regimen: "oficiales",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "FIDEOS CON SALSA ESTOFADO",
    postre: "FLAN",
    regimen: "oficiales",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "FIDEOS AL PESTO ACEITE, ALBAHACA, QUESO Y HAMBURGUESA CASERA",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "GELATINA",
    regimen: "oficiales",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "FLAN",
    regimen: "oficiales",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "EMPANADA DE CARNE(2) EMPANADA DE JYQ(2)",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "BIFE CON PURE MIXTO",
    postre: "GELATINA",
    regimen: "oficiales",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PIZZAS 4 PORCIONES",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
  },

  {
    id: 301,
    tipo: "almuerzo",
    principal: "BIFE CON POLENTA",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.175, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POLENTA", pb: 0.19, unidad: "kg" },
      { nombre: "HARINA DE MAÍZ", pb: 0.07, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO CON ARROZ BLANCO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PANACHE TRICOLOR",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA CON PURE DE ZAPALLO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. C/ TALLARINES",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "RAVIOLES CON SALSA BLANCA Y POLLO",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "GUISO DE CARNE CON VEGETALES",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL MIXTO",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "FIDEOS CON TALLARIN FILETTO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "ALBONDIGAS CON ARROZ BLANCO",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "POLENTA CON QUESO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "POLLO AL HORNO CON PANACHE TRICOLOR",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON ARROZ",
    postre: "FLAN",
    regimen: "blando gastrico",
  },

  {
    id: 401,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PURE DE PAPAS",
    postre: "GELATINA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON SOUFFLE DE ACELGA",
    postre: "ENS. DE FRUTA",
    regimen: "diabetico",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. CON ENSALADA",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA COCIDA CON ENS. REMOLACHA Y ZANAHORIA",
    postre: "ASPIC",
    regimen: "diabetico",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "FLAN",
    regimen: "diabetico",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. CON BUDIN BICOLOR",
    postre: "ENS. DE FRUTA",
    regimen: "diabetico",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "LASAGNA DE VERDURA Y RICOTTA CON SS MIXTA",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "MILANESA DE POLLO CON BERENJENAS C/ QUESO",
    postre: "FLAN",
    regimen: "diabetico",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL DE CALABAZA",
    postre: "NARANJA",
    regimen: "diabetico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "POSTRE",
    regimen: "diabetico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "WOK DE POLLO CON VERDURAS",
    postre: "MANZANA AL HORNO",
    regimen: "diabetico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "ZAPALLITO RELLENO CON CARNE Y ARROZ AMARILLO",
    postre: "GELATINA",
    regimen: "diabetico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "BIFE DE POLLO CON ENSALADA DE LEGUMBRES",
    postre: "POSTRE",
    regimen: "diabetico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON CALABAZA GRATINADA",
    postre: "ASPIC",
    regimen: "diabetico",
  },

  {
    id: 501,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PURE DE PAPAS",
    postre: "CHUÑO",
    regimen: "hiperproteico",
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "ARROZ CON POLLO",
    postre: "BANANA",
    regimen: "hiperproteico",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "CHORIZO A LA POMAROLA",
    postre: "QUESO Y DULCE",
    regimen: "hiperproteico",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE PRECOCIDA CON ARROZ AMARILLO",
    postre: "NARANJA",
    regimen: "hiperproteico",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "BUDIN DE PAN C/FLAN",
    regimen: "hiperproteico",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. CON FIDEOS",
    postre: "FLAN DE VAINILLA",
    regimen: "hiperproteico",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "RAVIOLES CON SALSA DE POLLO",
    postre: "BANANA",
    regimen: "hiperproteico",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "GUISO DE FIDEOS",
    postre: "FLAN",
    regimen: "hiperproteico",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "POSTRE DE VAINILLA",
    regimen: "hiperproteico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "FLAN DE VAINILLA",
    regimen: "hiperproteico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "POSTRE",
    regimen: "hiperproteico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "CHUÑO",
    regimen: "hiperproteico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "MONDONGO A LA BRETONA",
    postre: "COMPOTA MIXTA",
    regimen: "hiperproteico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON ARROZ BLANCO",
    postre: "FLAN DE VAINILLA",
    regimen: "hiperproteico",
  },

  {
    id: 601,
    tipo: "almuerzo",
    principal: "ARROZ CON POLLO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/PURE MIXTO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA C/ENSALADA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR.CON PURE MIXTO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ARROZ PRIMAVERA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "BANANA",
    regimen: "hiv",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "ALBONDIGAS CON SALSA Y PURE PURE DE PAPA Y BATATA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "MANDARINA",
    regimen: "hiv",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "NARANJA",
    regimen: "hiv",
  },

  {
    id: 701,
    tipo: "almuerzo",
    principal: "ALBONDIGA CON PURE CALABAZA",
    postre: "GELATINA",
    regimen: "celiaco",
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PANACHE DE VERDURA",
    postre: "FLAN DE VAINILLA",
    regimen: "celiaco",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "PASTEL DE CALABAZA DE CARNE",
    postre: "CHUÑO",
    regimen: "celiaco",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "HAMBURGUESA CASERA CON PURE DE CALABAZA",
    postre: "FLAN",
    regimen: "celiaco",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "celiaco",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON ZANAHORIA Y CALABAZA",
    postre: "DURAZNO",
    regimen: "celiaco",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "HAMBURGUESA CASERA DE CARNE CON TORTILLA DE ACELGA",
    postre: "GELATINA",
    regimen: "celiaco",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "FIDEO DE ARROZ CON ESTOFADO DE POLLO",
    postre: "MANZANA",
    regimen: "celiaco",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "SALPICON DE POLLO",
    postre: "DURAZNO",
    regimen: "celiaco",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "CHURRASCO CON ENSALADA DE LECHUGA Y TOMATE",
    postre: "BANANA",
    regimen: "celiaco",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "PASTEL MIXTO DE CARNE",
    postre: "MANZANA",
    regimen: "celiaco",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "ALBONDIGA DE POLLO CON ACELGA GRATINADA",
    postre: "BANANA",
    regimen: "celiaco",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "FIDEO DE ARROZ CON BOLOGNESA",
    postre: "NARANJA",
    regimen: "celiaco",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "HAMBURGUESA DE POLLO CON ARROZ",
    postre: "BANANA",
    regimen: "celiaco",
  },

  {
    id: 801,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PURE DE PAPAS",
    postre: "GELATINA MERENGADA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.05, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.05, unidad: "unidad" },
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "ARROZ CON POLLO",
    postre: "NARANJA",
    regimen: "hipercalorico",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "CHORIZO A LA POMAROLA",
    postre: "FLAN DE VAINILLA",
    regimen: "hipercalorico",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE PRECOCIDA CON ARROZ AMARILLO",
    postre: "NARANJA",
    regimen: "hipercalorico",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "NARANJA",
    regimen: "hipercalorico",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. CON FIDEOS",
    postre: "CHUÑO",
    regimen: "hipercalorico",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "RAVIOLES CON SALSA DE POLLO",
    postre: "FLAN C/DULCE DE LECHE",
    regimen: "hipercalorico",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "GUISO DE FIDEOS",
    postre: "FLAN DE VAINILLA",
    regimen: "hipercalorico",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "BUDIN DE PAN C/FLAN",
    regimen: "hipercalorico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "DURAZNO EN ALMIBAR",
    regimen: "hipercalorico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "POSTRE DE VAINILLA",
    regimen: "hipercalorico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "MANZANA",
    regimen: "hipercalorico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "MONDONGO A LA BRETONA",
    postre: "GELATINA MERENGADA",
    regimen: "hipercalorico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON ARROZ BLANCO",
    postre: "BANANA",
    regimen: "hipercalorico",
  },
];
