const menus = [
  {
    id: 101,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ JARDINERA",
    postre: "NARANJA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.03, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.125, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.007, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },

  {
    id: 102,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ JARDINERA",
    postre: "NARANJA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ARVEJA SECA", pb: 0.03, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.125, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.007, unidad: "kg" },
      { nombre: "POLLO 8 CABEZAS", pb: 0.416, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },

  {
    id: 103,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "ASPIC",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.02, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.08, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "MANZANA ROJA COMERCIAL", pb: 0.05, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR ASPIC", pb: 0.015, unidad: "kg" },
    ],
  },
  {
    id: 104,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA C/ENSALADA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.12, unidad: "kg" },
      { nombre: "MILANESA PRECOCIDA", pb: 1.0, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 105,
    tipo: "almuerzo",
    principal: "ASADO C/ ENSALADA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 106,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUST. C/PURE MIXTO",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.06, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.14, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "HAMBURGUESAS", pb: 2.0, unidad: "unidades" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 107,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ARROZ PRIMAVERA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.5, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 108,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "BANANA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TALLARIN", pb: 0.09, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.015, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 109,
    tipo: "cena",
    principal: "ALBONDIGAS CON SALSA Y PURE PURE DE PAPA Y BATATA",
    postre: "FLAN",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "BATATA", pb: 0.2, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.25, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 110,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAPA BLANCA", pb: 0.48, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 111,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "POSTRE",
    regimen: "general",
    ingredientes: [
      { nombre: "ARROZ BLANCO 00000", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.38, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POSTRE", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 112,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "POSTRE",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO GUISERO", pb: 0.1, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POSTRE", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 113,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "CHUÑO",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.008, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE MAIZ", pb: 0.07, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.01, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.015, unidad: "kg" },
    ],
  },
  {
    id: 114,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "BATATA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.03, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 201,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ SALSA Y ENSALADA JARDINERA",
    postre: "Fruta",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.03, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.125, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.007, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 202,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON SALSA CRIOLLA Y PAPAS AL NATURAL",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PAPA BLANCA", pb: 0.38, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.378, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.06, unidad: "kg" },
      { nombre: "MORRON ROJO", pb: 0.02, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 203,
    tipo: "almuerzo",
    principal: "MILANESA CASERA CON ENSALADA",
    postre: "FLAN DE VAINILLA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.09, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "HUEVOS", pb: 0.25, unidad: "unidad" },
      { nombre: "NALGA FETEADA X 120", pb: 0.12, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },

  {
    id: 204,
    tipo: "almuerzo",
    principal: "ALBONDIGAS CON FIDEOS",
    postre: "FRUTA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO GUISERO", pb: 0.1, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.005, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 205,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 206,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON VERDURAS EN JULIANA",
    postre: "FLAN",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "POLLO 10 CABEZAS", pb: 0.5, unidad: "kg" },
      { nombre: "BERENJENA", pb: 0.1, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON ROJO", pb: 0.03, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.07, unidad: "kg" },
      { nombre: "ZAPALLITO CORTE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 207,
    tipo: "almuerzo",
    principal: "RAVIOLES DE VERDURA CON ESTOFADO",
    postre: "FLAN DE VAINILLA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "RAVIOLES DE VERDURA", pb: 0.17, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 208,
    tipo: "cena",
    principal: "FIDEOS CON SALSA ESTOFADO",
    postre: "FLAN",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TALLARIN", pb: 0.12, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "OREGANO", pb: 0.0, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.005, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.14, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 209,
    tipo: "cena",
    principal: "FIDEOS AL PESTO ACEITE, ALBAHACA, QUESO Y HAMBURGUESA CASERA",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.015, unidad: "litros" },
      { nombre: "ALBAHACA", pb: 0.01, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TALLARIN", pb: 0.1, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.007, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CARNE PICADA ESPECIAL", pb: 0.15, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 210,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAPA BLANCA", pb: 0.48, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 211,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "FLAN",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ARROZ BLANCO 00000", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.38, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 212,
    tipo: "cena",
    principal: "EMPANADA DE CARNE(2) EMPANADA DE JYQ(2)",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "ACEITUNA VERDE", pb: 0.008, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.04, unidad: "unidad" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "TAPA DE EMPANADA", pb: 0.08, unidad: "unidad" },
      { nombre: "HUEVOS", pb: 0.04, unidad: "unidad" },
      { nombre: "PALETA COCIDA", pb: 0.08, unidad: "kg" },
      { nombre: "QUESO BARRA", pb: 0.08, unidad: "kg" },
      { nombre: "TAPA DE EMPANADA", pb: 0.2, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 213,
    tipo: "cena",
    principal: "BIFE CON PURE MIXTO",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.22, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.005, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.005, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.3, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.2, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 214,
    tipo: "cena",
    principal: "PIZZAS 4 PORCIONES",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "AZUCAR BLANCA", pb: 0.03, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "HARINA DE TRIGO 000", pb: 0.16, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "LEVADURA SECA", pb: 0.03, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO MOZZARELLA", pb: 0.12, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },

  {
    id: 301,
    tipo: "almuerzo",
    principal: "BIFE C/ POLENTA",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.176, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR PURE", pb: 0.01, unidad: "kg" },
      { nombre: "HARINA DE MAIZ", pb: 0.07, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 302,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ ARROZ",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.08, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.007, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.018, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 303,
    tipo: "almuerzo",
    principal: "BIFE C/ PANACHE",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.176, unidad: "kg" },
      { nombre: "ACELGA", pb: 0.12, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.09, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.11, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 304,
    tipo: "almuerzo",
    principal: "PATYNESA C/ P DE CALABAZA",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "PATYNESA", pb: 1.0, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.4, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 305,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.06, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 306,
    tipo: "almuerzo",
    principal: "HAMBUR C/ FIDEOS",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "FIDEO SEMOLADO", pb: 0.09, unidad: "kg" },
      { nombre: "HAMBURGUESAS", pb: 2.0, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 307,
    tipo: "almuerzo",
    principal: "RAVIOLES CON SALSA BLANCA Y POLLO",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "HARINA DE TRIGO", pb: 0.01, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.003, unidad: "kg" },
      { nombre: "POLLO 8 CABEZAS", pb: 0.18, unidad: "kg" },
      { nombre: "RAVIOLES DE RICOTA", pb: 0.18, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },

  {
    id: 308,
    tipo: "cena",
    principal: "GUISO DE CARNE C/ VERDURAS",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.05, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
      { nombre: "ZAPALLITO CORTE", pb: 0.1, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.1, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 309,
    tipo: "cena",
    principal: "PASTEL MIXTO",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.005, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.2, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.2, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 310,
    tipo: "cena",
    principal: "TALLARINES CON FILETO",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.1, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 311,
    tipo: "cena",
    principal: "ALBONDIGAS C/ ARROZ",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.015, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.13, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.03, unidad: "kg" },
      { nombre: "QUESO BLANCO SIN SAL", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 312,
    tipo: "cena",
    principal: "POLENTA C/ QUESO",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "HARINA DE MAIZ", pb: 0.09, unidad: "kg" },
      { nombre: "QUESO CREMOSO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 313,
    tipo: "cena",
    principal: "POLLO AL HORNO C/ PANACHE",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "ACELGA", pb: 0.18, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.09, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.12, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.45, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 314,
    tipo: "cena",
    principal: "PAN DE CARNE C/ ARROZ",
    postre: "FLAN",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.01, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.18, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 401,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PURE DE PAPAS",
    postre: "GELATINA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.168, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.005, unidad: "kg" },
    ],
  },
  {
    id: 402,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON SUFFLE DE ACELGA",
    postre: "ENSALADA DE FRUTAS",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "POLLO 10 CABEZAS", pb: 0.378, unidad: "kg" },
      { nombre: "ACELGA", pb: 0.4, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.09, unidad: "kg" },
      { nombre: "QUESO CREMOSO", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DURAZNO EN ALMIBAR", pb: 0.02, unidad: "kg" },
      { nombre: "EDULCORANTE LIQUIDO", pb: 0.003, unidad: "litros" },
      { nombre: "MANZANA ROJA COCIDA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.04, unidad: "kg" },
    ],
  },
  {
    id: 403,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS CON ENSALADA",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.125, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
      { nombre: "HAMBURGUESA DE CARNE", pb: 2.0, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "EDULCORANTE LIQUIDO", pb: 0.005, unidad: "litros" },
      { nombre: "MANZANA ROJA COCIDA", pb: 0.18, unidad: "kg" },
    ],
  },
  {
    id: 404,
    tipo: "almuerzo",
    principal: "PATYNESA CON ENSALADA",
    postre: "ASPIC",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "kg" },
      { nombre: "REMOLACHA", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.15, unidad: "kg" },
      { nombre: "PATYNESA", pb: 1.0, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "MANZANA ROJA COCIDA", pb: 0.06, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 405,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "FRUTA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 406,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS CON BUDIN BICOLOR",
    postre: "ENSALADA DE FRUTA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.004, unidad: "litros" },
      { nombre: "ACELGA", pb: 0.3, unidad: "kg" },
      { nombre: "ALMIDON DE MAIZ", pb: 0.004, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.007, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.25, unidad: "kg" },
      { nombre: "HAMBURGUESA DE CARNE", pb: 2.0, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "BANANA", pb: 0.06, unidad: "kg" },
      { nombre: "DURAZNO EN ALMIBAR", pb: 0.02, unidad: "kg" },
      { nombre: "EDULCORANTE LIQUIDO", pb: 0.003, unidad: "litros" },
      { nombre: "MANZANA ROJA COCIDA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.04, unidad: "kg" },
    ],
  },
  {
    id: 407,
    tipo: "almuerzo",
    principal: "LASAÑA",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACELGA", pb: 0.35, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE TRIGO", pb: 0.08, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.023, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.02, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.07, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.01, unidad: "kg" },
      { nombre: "RICOTTA ENTERA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "EDULCORANTE LIQUIDO", pb: 0.005, unidad: "litros" },
      { nombre: "MANZANA ROJA COCIDA", pb: 0.18, unidad: "kg" },
    ],
  },

  {
    id: 408,
    tipo: "cena",
    principal: "MILANESA DE POLLO CON BERENJENA NAPOLITANA",
    postre: "FLAN",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "RICOTTA ENTERA", pb: 0.04, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "BERENJENA", pb: 0.22, unidad: "kg" },
      { nombre: "QUESO CREMOSO", pb: 0.03, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.02, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.4, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.06, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.312, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.015, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.0045, unidad: "kg" },
    ],
  },
  {
    id: 409,
    tipo: "cena",
    principal: "PASTEL DE CALABAZA",
    postre: "FRUTA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.15, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.15, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.4, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 410,
    tipo: "cena",
    principal: "GUISO DE LENTEJA",
    postre: "FLAN",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.08, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.015, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.0045, unidad: "kg" },
    ],
  },
  {
    id: 411,
    tipo: "cena",
    principal: "WOK DE POLLO",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "BERENJENA", pb: 0.09, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "POLLO 8 CABEZAS", pb: 0.225, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "ZAPALLITO CORTE", pb: 0.1, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "EDULCORANTE LÍQUIDO", pb: 0.002, unidad: "kg" },
      { nombre: "MANZANA ROJA COCIDA", pb: 0.15, unidad: "kg" },
    ],
  },
  {
    id: 412,
    tipo: "cena",
    principal: "ZAPALLITO RELLENO Y ARROZ AMARILLO",
    postre: "GELATINA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ARROZ PARBOLIZADO", pb: 0.05, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.02, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.1, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.04, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.02, unidad: "kg" },
      { nombre: "ZAPALLITO REDONDO", pb: 0.25, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.005, unidad: "kg" },
    ],
  },
  {
    id: 413,
    tipo: "cena",
    principal: "POLLO GRILLE Y ENSALADA DE LEGUMBRES",
    postre: "FLAN",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "CEBOLLA DE VERDEO", pb: 0.01, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.06, unidad: "kg" },
      { nombre: "MORRON ROJO", pb: 0.03, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.02, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "POLLO 8 CABEZAS", pb: 0.42, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE DESCREMADA EN POLVO", pb: 0.008, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.004, unidad: "kg" },
    ],
  },
  {
    id: 414,
    tipo: "cena",
    principal: "PAN DE CARNE CON CALABAZA GRATINADA",
    postre: "ASPIC",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "QUESO CREMOSO", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.34, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.025, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "MANZANA ROJA COCIDA", pb: 0.06, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR ASPIC", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 501,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PURE",
    postre: "CHUÑO",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "PALETA SIN TAPA", pb: 0.25, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 502,
    tipo: "almuerzo",
    principal: "ARROZ CON POLLO",
    postre: "FRUTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "APIO", pb: 0.005, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA DE VERDEO", pb: 0.05, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.342, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 503,
    tipo: "almuerzo",
    principal: "CHORIZO A LA PORMAROLA CON PURE DE PAPA",
    postre: "QUESO Y DULCE",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHORIZO CRIOLLO", pb: 0.26, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.4, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE BATATA", pb: 0.025, unidad: "kg" },
      { nombre: "DULCE DE MEMBRILLO", pb: 0.025, unidad: "kg" },
      { nombre: "QUESO CREMOSO", pb: 0.05, unidad: "kg" },
    ],
  },
  {
    id: 504,
    tipo: "almuerzo",
    principal: "PATYNESA C/ ENSALADA",
    postre: "FRUTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.12, unidad: "kg" },
      { nombre: "PATYNESA", pb: 1.0, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 505,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "BUDIN DE PAN",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.04, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.04, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "HUEVOS", pb: 0.6, unidad: "unidad" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 506,
    tipo: "almuerzo",
    principal: "HAMBURGUESA C/ ENSALADA",
    postre: "FLAN CON CARAMELO",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ALBAHACA", pb: 0.01, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TAL", pb: 0.1, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.008, unidad: "kg" },
      { nombre: "HAMBURGUESA DE CARNE", pb: 2.0, unidad: "unidad" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 507,
    tipo: "almuerzo",
    principal: "RAVIOLES C/ ESTOFADO DE POLLO",
    postre: "FRUTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.2, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "RAVIOLES DE VERDURA", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 508,
    tipo: "cena",
    principal: "GUISO DE FIDEOS",
    postre: "FLAN",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.09, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 509,
    tipo: "cena",
    principal: "PASTEL DE PAPAS",
    postre: "POSTRE DE VAINILLA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.25, unidad: "unidad" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.5, unidad: "kg" },
      { nombre: "PUERRO", pb: 0.005, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.18, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 510,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "FLAN CON DDL",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.1, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.08, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE LECHE", pb: 0.01, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 511,
    tipo: "cena",
    principal: "POLENTA CON BOLOGÑESA",
    postre: "POSTRE",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.003, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE MAIZ", pb: 0.06, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.008, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.064, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 512,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "CHUÑO",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "BATATA", pb: 0.03, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHOCLO EN GRANO", pb: 0.015, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.1, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.03, unidad: "kg" },
      { nombre: "PULPA DE JAMÓN", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDÓN DE MAÍZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZÚCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 513,
    tipo: "cena",
    principal: "MONDONGO A LA BRETONA",
    postre: "COMPOTA MIXTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.02, unidad: "kg" },
      { nombre: "GARBANZO", pb: 0.03, unidad: "kg" },
      { nombre: "MONDONGO", pb: 0.15, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.02, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.1, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "CIRUELA DESHIDRATADA", pb: 0.03, unidad: "kg" },
      { nombre: "EDULCORANTE LÍQUIDO", pb: 0.005, unidad: "litros" },
      { nombre: "MANZANA ROJA C/D", pb: 0.12, unidad: "kg" },
    ],
  },
  {
    id: 514,
    tipo: "cena",
    principal: "PAN DE CARNE C/ ARROZ BLANCO",
    postre: "FLAN",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "MANTECA", pb: 0.005, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.01, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL (extra)", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.025, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.05, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 601,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PURE",
    postre: "NARANJA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "PALETA SIN TAPA", pb: 0.128, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.35, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "NARANJA", pb: 1, unidad: "unidad" }],
  },
  {
    id: 602,
    tipo: "almuerzo",
    principal: "MEDALLON DE POLLO C/ PURE MIXTO",
    postre: "GELATINA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "MEDALLON DE POLLO", pb: 2.0, unidad: "unidad" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PAPA BLANCA", pb: 0.25, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.19, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 603,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "ASPIC",
    regimen: "hiv",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.025, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.03, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.06, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA", pb: 0.05, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.025, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "BANANA", pb: 0.1, unidad: "unidad" },
      { nombre: "MANZANA ROJA C/D", pb: 0.1, unidad: "unidad" },
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 604,
    tipo: "almuerzo",
    principal: "PATYNESA C/ ENSALADA",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.09, unidad: "kg" },
      { nombre: "MILANESA DE CARNE", pb: 1.0, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.12, unidad: "kg" }],
  },
  {
    id: 605,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.12, unidad: "kg" }],
  },
  {
    id: 606,
    tipo: "almuerzo",
    principal: "ALBONDIGAS CON PURE DE ZANAHORIAS",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.1, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.14, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 607,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON ARROZ PRIMAVERA",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.5, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 608,
    tipo: "cena",
    principal: "TALLARINES C/ ESTOFADO",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.1, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.015, unidad: "kg" },
      { nombre: "PULPA DE JAMÓN C.", pb: 0.1, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 609,
    tipo: "cena",
    principal: "ALBONDIGAS C/ PURE MIXTO",
    postre: "FLAN",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.1, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
      { nombre: "BATATA", pb: 0.1, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 610,
    tipo: "cena",
    principal: "PASTEL DE PAPAS",
    postre: "ENSALADA DE FRUTAS",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAPA BLANCA", pb: 0.38, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.096, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "BANANA", pb: 0.066, unidad: "unidad" },
      { nombre: "MANZANA ROJA C/D", pb: 0.066, unidad: "unidad" },
      { nombre: "NARANJA", pb: 0.066, unidad: "unidad" },
    ],
  },
  {
    id: 611,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "POSTRE",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ARROZ PARBOLIZADO", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.012, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.003, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.342, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POSTRE", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 612,
    tipo: "cena",
    principal: "TALLARINES CON ESTOFADO",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.1, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.015, unidad: "kg" },
      { nombre: "PULPA DE JAMÓN", pb: 0.1, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 613,
    tipo: "cena",
    principal: "POLENTA C/ BOLOGNESA",
    postre: "CHUÑO",
    regimen: "hiv",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.003, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE MAIZ", pb: 0.07, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.007, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.064, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 614,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "FRUTA",
    regimen: "hiv",
    ingredientes: [
      { nombre: "BATATA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CUERITO DE CERDO", pb: 0.0265, unidad: "kg" },
      { nombre: "MONDONGO", pb: 0.055, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.15, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.12, unidad: "kg" }],
  },
  {
    id: 701,
    tipo: "almuerzo",
    principal: "ALBONDIGAS C/ PURE ZAPALLO",
    postre: "GELATINA",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.005, unidad: "litros" },
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "RECORTE", pb: 0.104, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ZAPALLO ANCO", pb: 0.45, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.015, unidad: "kg" },
    ],
  },
  {
    id: 702,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PANACHE",
    postre: "FLAN",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "PALETA SIN TAPA", pb: 0.176, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ACELGA", pb: 0.18, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.14, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.15, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 703,
    tipo: "almuerzo",
    principal: "PASTEL DE CALABAZA",
    postre: "CHUÑO",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.15, unidad: "unidad" },
      { nombre: "MORRON VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.4, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.0135, unidad: "kg" },
    ],
  },
  {
    id: 704,
    tipo: "almuerzo",
    principal: "HAMBURGUESA C/ PURE ZAPALLO",
    postre: "FLAN",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.01, unidad: "litros" },
      { nombre: "ZAPALLO ANCO", pb: 0.45, unidad: "kg" },
      { nombre: "HAMBURGUESA SIN TACC", pb: 2.0, unidad: "unidad" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 705,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "ASADO DE TIRA", pb: 0.46, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.1, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.015, unidad: "kg" },
    ],
  },
  {
    id: 706,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PURE ZANAHORIA Y ZAPALLO",
    postre: "DURAZNO EN ALMIBAR",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "ZANAHORIA", pb: 0.115, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.266, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.176, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DURAZNO EN ALMIBAR", pb: 0.15, unidad: "unidad" },
    ],
  },
  {
    id: 707,
    tipo: "almuerzo",
    principal: "HAMBUR.C/ TORTILLA DE ACELGA",
    postre: "GELATINA",
    regimen: "celiaco",
    ingredientes: [
      { nombre: "HAMBURGUESAS SIN TACC", pb: 2.0, unidad: "unidad" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ACELGA", pb: 0.3, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.015, unidad: "kg" },
    ],
  },
  [
    {
      id: 708,
      momento: "cena",
      régimen: "celiaco",
      plato: "FIDEOS C/ ESTOFADO DE POLLO",
      ingredientes: [
        { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.002 },
        { nombre: "CEBOLLA", pb: 0.04 },
        { nombre: "FIDEO DE ARROZ SIN TACC", pb: 0.15 },
        { nombre: "MORRON VERDE", pb: 0.007 },
        { nombre: "POLLO 10 CABEZAS", pb: 0.279 },
        { nombre: "PURE DE TOMATE", pb: 0.05 },
        { nombre: "ZANAHORIA", pb: 0.015 },
      ],
      postre: {
        nombre: "FRUTA",
        ingredientes: [{ nombre: "FRUTA", pb: 0.18 }],
      },
    },
    {
      id: 709,
      momento: "cena",
      régimen: "celiaco",
      plato: "SALPICÓN DE POLLO",
      ingredientes: [
        { nombre: "ARROZ PARBOLIZADO", pb: 0.09 },
        { nombre: "ARVEJA REMOJADA", pb: 0.02 },
        { nombre: "HUEVOS", pb: 0.1 },
        { nombre: "LECHUGA", pb: 0.02 },
        { nombre: "MORRON VERDE", pb: 0.008 },
        { nombre: "PAPA BLANCA", pb: 0.04 },
        { nombre: "POLLO 10 CABEZAS", pb: 0.162 },
        { nombre: "ZANAHORIA", pb: 0.04 },
      ],
      postre: {
        nombre: "DURAZNO EN ALMIBAR SIN TACC",
        ingredientes: [{ nombre: "DURAZNO EN ALMIBAR", pb: 0.15 }],
      },
    },
    {
      id: 710,
      momento: "cena",
      régimen: "celiaco",
      plato: "CHURRASCO C/ ENSALADA",
      ingredientes: [
        { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.005 },
        { nombre: "LECHUGA", pb: 0.08 },
        { nombre: "PALETA SIN TAPA", pb: 0.12 },
        { nombre: "TOMATE", pb: 0.12 },
        { nombre: "MANZANA ROJA C/ PIEL", pb: 0.18 },
      ],
      postre: {
        nombre: "FRUTA",
        ingredientes: [{ nombre: "FRUTA", pb: 0.18 }],
      },
    },
    {
      id: 711,
      momento: "cena",
      régimen: "celiaco",
      plato: "PASTEL MIXTO",
      ingredientes: [
        { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.005 },
        { nombre: "CEBOLLA", pb: 0.01 },
        { nombre: "HUEVOS", pb: 0.2 },
        { nombre: "LECHE ENTERA EN POLVO", pb: 0.005 },
        { nombre: "PAPA BLANCA", pb: 0.2 },
        { nombre: "RECORTE", pb: 0.12 },
        { nombre: "ZAPALLO ANCO", pb: 0.2 },
      ],
      postre: {
        nombre: "FRUTA",
        ingredientes: [{ nombre: "FRUTA", pb: 0.18 }],
      },
    },
    {
      id: 712,
      momento: "cena",
      régimen: "celiaco",
      plato: "ALBONDIGA DE POLLO C/ ACELGA GRATINADA",
      ingredientes: [
        { nombre: "ACEITE DE GIRASOL", pb: 0.005 },
        { nombre: "ACELGA", pb: 0.4 },
        { nombre: "HUEVOS", pb: 0.1 },
        { nombre: "QUESO CREMOSO SIN TACC", pb: 0.05 },
        { nombre: "ACEITE DE GIRASOL", pb: 0.015 },
        { nombre: "ALMIDÓN DE MAIZ", pb: 0.015 },
        { nombre: "HUEVOS", pb: 0.2 },
        { nombre: "POLLO 10 CABEZAS", pb: 0.45 },
      ],
      postre: {
        nombre: "FRUTA",
        ingredientes: [{ nombre: "FRUTA", pb: 0.18 }],
      },
    },
    {
      id: 713,
      momento: "cena",
      régimen: "celiaco",
      plato: "FIDEOS CON BOLOGNESA",
      ingredientes: [
        { nombre: "ACEITE MEZCLA SIN TACC", pb: 0.002 },
        { nombre: "CEBOLLA", pb: 0.04 },
        { nombre: "FIDEO DE ARROZ SIN TACC", pb: 0.15 },
        { nombre: "MORRON VERDE", pb: 0.007 },
        { nombre: "PURE DE TOMATE", pb: 0.05 },
        { nombre: "RECORTE", pb: 0.05 },
        { nombre: "ZANAHORIA", pb: 0.015 },
      ],
      postre: {
        nombre: "FRUTA",
        ingredientes: [{ nombre: "FRUTA", pb: 0.18 }],
      },
    },
    {
      id: 714,
      momento: "cena",
      régimen: "celiaco",
      plato: "HAMBURGUESA DE POLLO C/ ARROZ BLANCO",
      ingredientes: [
        { nombre: "ALMIDÓN DE MAIZ", pb: 0.01 },
        { nombre: "ARROZ PARBOLIZADO", pb: 0.1 },
        { nombre: "CEBOLLA", pb: 0.01 },
        { nombre: "HUEVOS", pb: 0.3 },
        { nombre: "POLLO 10 CABEZAS", pb: 0.45 },
      ],
      postre: {
        nombre: "FRUTA",
        ingredientes: [{ nombre: "FRUTA", pb: 0.18 }],
      },
    },
  ],
  {
    id: 801,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PURE",
    postre: "GELATINA MERENGADA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.168, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.005, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.5, unidad: "unidad" },
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.025, unidad: "kg" },
    ],
  },
  {
    id: 802,
    tipo: "almuerzo",
    principal: "ARROZ C/ POLLO",
    postre: "FRUTA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "APIO", pb: 0.005, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA DE VERDEO", pb: 0.005, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.342, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 803,
    tipo: "almuerzo",
    principal: "CHORIZO A LA POMAROLA C/ PAPAS",
    postre: "FLAN C/ CARAMELO",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHORIZO CRIOLLO", pb: 0.26, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.4, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 804,
    tipo: "almuerzo",
    principal: "PATYNESA C/ ARROZ AMARILLO",
    postre: "FRUTA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.02, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MANTECA", pb: 0.005, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PATYNESA", pb: 1.0, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 805,
    tipo: "almuerzo",
    principal: "ASADO C/ ENSALADA",
    postre: "BUDIN DE PAN",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.04, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.7, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 806,
    tipo: "almuerzo",
    principal: "HAMBURGUESA C/ FIDEOS AL PESTO",
    postre: "CHUÑO",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "kg" },
      { nombre: "ALBAHACA", pb: 0.01, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.1, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.008, unidad: "kg" },
      { nombre: "HAMBURGUESA DE CARNE", pb: 0.2, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.01, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 807,
    tipo: "almuerzo",
    principal: "RAVIOLES C/ ESTOFADO DE POLLO",
    postre: "FLAN C/ CARAMELO",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.207, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "RAVIOLES DE VERDURA", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE LECHE", pb: 0.01, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },

  {
    id: 808,
    tipo: "cena",
    principal: "GUISO DE FIDEOS",
    postre: "FLAN CON CARAMELO",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.1, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.02, unidad: "kg" },
      { nombre: "PURÉ DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.05, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.01, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 809,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "DURAZNO CON DULCE DE LECHE",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.01, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.01, unidad: "kg" },
      { nombre: "PURÉ DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.05, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE LECHE", pb: 0.02, unidad: "kg" },
      { nombre: "DURAZNO EN ALMÍBAR", pb: 0.15, unidad: "kg" },
    ],
  },
  {
    id: 810,
    tipo: "cena",
    principal: "POLENTA CON BOLOGNESA",
    postre: "POSTRE DE VAINILLA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.003, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE MAÍZ", pb: 0.08, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "PURÉ DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.008, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.064, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 811,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "FRUTA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "BATATA", pb: 0.03, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHOCLO EN GRANOS", pb: 0.01, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.03, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.06, unidad: "kg" },
      { nombre: "PULPA DE JAMÓN", pb: 0.12, unidad: "kg" },
      { nombre: "PURÉ DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 812,
    tipo: "cena",
    principal: "MONDONGO A LA BRETONA",
    postre: "GELATINA MERENGADA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.01, unidad: "kg" },
      { nombre: "GARBANZO", pb: 0.05, unidad: "kg" },
      { nombre: "MONDONGO", pb: 0.15, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.02, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.03, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.06, unidad: "kg" },
      { nombre: "PURÉ DE TOMATE", pb: 0.025, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.025, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.05, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 813,
    tipo: "cena",
    principal: "PAN DE CARNE CON ARROZ BLANCO",
    postre: "FRUTA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "MANTECA", pb: 0.005, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.01, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.03, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.01, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.05, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 814,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "BUDIN DE PAN",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.01, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.01, unidad: "kg" },
      { nombre: "PURÉ DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.05, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.04, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.06, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
];
localStorage.setItem("comida", JSON.stringify(menus));
