const menus = [
  {
    id: 101,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ JARDINERA",
    postre: "NARANJA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },

  {
    id: 102,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ JARDINERA",
    postre: "NARANJA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ARVEJA SECA", pb: 0.03, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.125, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.007, unidad: "kg" },
      { nombre: "POLLO 8 CABEZAS", pb: 0.416, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },

  {
    id: 103,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "ASPIC",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.02, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.08, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "MANZANA ROJA COMERCIAL", pb: 0.05, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR ASPIC", pb: 0.015, unidad: "kg" },
    ],
  },
  {
    id: 104,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA C/ENSALADA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.12, unidad: "kg" },
      { nombre: "MILANESA PRECOCIDA", pb: 1.0, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 105,
    tipo: "almuerzo",
    principal: "ASADO C/ ENSALADA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 106,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUST. C/PURE MIXTO",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.06, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.14, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "HAMBURGUESAS", pb: 2.0, unidad: "unidades" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 107,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ARROZ PRIMAVERA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.5, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.15, unidad: "kg" }],
  },
  {
    id: 108,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "BANANA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TALLARIN", pb: 0.09, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.015, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 109,
    tipo: "cena",
    principal: "ALBONDIGAS CON SALSA Y PURE PURE DE PAPA Y BATATA",
    postre: "FLAN",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "BATATA", pb: 0.2, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.25, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 110,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAPA BLANCA", pb: 0.48, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 111,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "POSTRE",
    regimen: "general",
    ingredientes: [
      { nombre: "ARROZ BLANCO 00000", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.38, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POSTRE", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 112,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "POSTRE",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO GUISERO", pb: 0.1, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POSTRE", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 113,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "CHUÑO",
    regimen: "general",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.008, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE MAIZ", pb: 0.07, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.01, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.015, unidad: "kg" },
    ],
  },
  {
    id: 114,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "FRUTA",
    regimen: "general",
    ingredientes: [
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "BATATA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.15, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.03, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 201,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ SALSA Y ENSALADA JARDINERA",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "AZUCAR BLANCA", pb: 0.003, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "HARINA DE TRIGO 000", pb: 0.16, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "LEVADURA SECA", pb: 0.003, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO MOZZARELLA", pb: 0.18, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 202,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON SALSA CRIOLLA Y PAPAS AL NATURAL",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PAPA BLANCA", pb: 0.38, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.378, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.06, unidad: "kg" },
      { nombre: "MORRON ROJO", pb: 0.02, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 203,
    tipo: "almuerzo",
    principal: "MILANESA CASERA CON ENSALADA",
    postre: "FLAN DE VAINILLA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.09, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "HUEVOS", pb: 0.25, unidad: "unidad" },
      { nombre: "NALGA FETEADA X 120", pb: 0.12, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },

  {
    id: 204,
    tipo: "almuerzo",
    principal: "ALBONDIGAS CON FIDEOS",
    postre: "FRUTA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO GUISERO", pb: 0.1, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.005, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAN RALLADO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 205,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 206,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON VERDURAS EN JULIANA",
    postre: "FLAN",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "POLLO 10 CABEZAS", pb: 0.5, unidad: "kg" },
      { nombre: "BERENJENA", pb: 0.1, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON ROJO", pb: 0.03, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.07, unidad: "kg" },
      { nombre: "ZAPALLITO CORTE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 207,
    tipo: "almuerzo",
    principal: "RAVIOLES DE VERDURA CON ESTOFADO",
    postre: "FLAN DE VAINILLA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "RAVIOLES DE VERDURA", pb: 0.17, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 208,
    tipo: "cena",
    principal: "FIDEOS CON SALSA ESTOFADO",
    postre: "FLAN",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TALLARIN", pb: 0.12, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "OREGANO", pb: 0.0, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.005, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.14, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.012, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 209,
    tipo: "cena",
    principal: "FIDEOS AL PESTO ACEITE, ALBAHACA, QUESO Y HAMBURGUESA CASERA",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.015, unidad: "litros" },
      { nombre: "ALBAHACA", pb: 0.01, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TALLARIN", pb: 0.1, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.007, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CARNE PICADA ESPECIAL", pb: 0.15, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 210,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAPA BLANCA", pb: 0.48, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.12, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 211,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "FLAN",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ARROZ BLANCO 00000", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.38, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 212,
    tipo: "cena",
    principal: "EMPANADA DE CARNE(2) EMPANADA DE JYQ(2)",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "ACEITUNA VERDE", pb: 0.008, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.04, unidad: "unidad" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.1, unidad: "kg" },
      { nombre: "TAPA DE EMPANADA", pb: 0.08, unidad: "unidad" },
      { nombre: "HUEVOS", pb: 0.04, unidad: "unidad" },
      { nombre: "PALETA COCIDA", pb: 0.08, unidad: "kg" },
      { nombre: "QUESO BARRA", pb: 0.08, unidad: "kg" },
      { nombre: "TAPA DE EMPANADA", pb: 0.2, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 213,
    tipo: "cena",
    principal: "BIFE CON PURE MIXTO",
    postre: "GELATINA",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.22, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.005, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.005, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.3, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.2, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 214,
    tipo: "cena",
    principal: "PIZZAS 4 PORCIONES",
    postre: "ENS. DE FRUTAS",
    regimen: "oficiales",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.02, unidad: "litros" },
      { nombre: "AZUCAR BLANCA", pb: 0.03, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "HARINA DE TRIGO 000", pb: 0.16, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.2, unidad: "unidad" },
      { nombre: "LEVADURA SECA", pb: 0.03, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO MOZZARELLA", pb: 0.12, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 301,
    tipo: "almuerzo",
    principal: "BIFE CON POLENTA",
    postre: "GELATINA",
    regimen: "blando gastrico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "PALETA SIN TAPA", pb: 0.175, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR POLENTA", pb: 0.19, unidad: "kg" },
      { nombre: "HARINA DE MAÍZ", pb: 0.07, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO CON ARROZ BLANCO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PANACHE TRICOLOR",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA CON PURE DE ZAPALLO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. C/ TALLARINES",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "RAVIOLES CON SALSA BLANCA Y POLLO",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "GUISO DE CARNE CON VEGETALES",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL MIXTO",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "FIDEOS CON TALLARIN FILETTO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "ALBONDIGAS CON ARROZ BLANCO",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "POLENTA CON QUESO",
    postre: "FLAN",
    regimen: "blando gastrico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "POLLO AL HORNO CON PANACHE TRICOLOR",
    postre: "GELATINA",
    regimen: "blando gastrico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON ARROZ",
    postre: "FLAN",
    regimen: "blando gastrico",
  },

  {
    id: 401,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PURE DE PAPAS",
    postre: "GELATINA",
    regimen: "diabetico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.16, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO CON SOUFFLE DE ACELGA",
    postre: "ENS. DE FRUTA",
    regimen: "diabetico",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. CON ENSALADA",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA COCIDA CON ENS. REMOLACHA Y ZANAHORIA",
    postre: "ASPIC",
    regimen: "diabetico",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "FLAN",
    regimen: "diabetico",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR. CON BUDIN BICOLOR",
    postre: "ENS. DE FRUTA",
    regimen: "diabetico",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "LASAGNA DE VERDURA Y RICOTTA CON SS MIXTA",
    postre: "COMPOTA DE MANZANA",
    regimen: "diabetico",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "MILANESA DE POLLO CON BERENJENAS C/ QUESO",
    postre: "FLAN",
    regimen: "diabetico",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL DE CALABAZA",
    postre: "NARANJA",
    regimen: "diabetico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "POSTRE",
    regimen: "diabetico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "WOK DE POLLO CON VERDURAS",
    postre: "MANZANA AL HORNO",
    regimen: "diabetico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "ZAPALLITO RELLENO CON CARNE Y ARROZ AMARILLO",
    postre: "GELATINA",
    regimen: "diabetico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "BIFE DE POLLO CON ENSALADA DE LEGUMBRES",
    postre: "POSTRE",
    regimen: "diabetico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON CALABAZA GRATINADA",
    postre: "ASPIC",
    regimen: "diabetico",
  },

  {
    id: 501,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PURE",
    postre: "CHUÑO",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "PALETA SIN TAPA", pb: 0.25, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDON DE MAIZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZUCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 502,
    tipo: "almuerzo",
    principal: "ARROZ CON POLLO",
    postre: "FRUTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "APIO", pb: 0.005, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA DE VERDEO", pb: 0.05, unidad: "kg" },
      { nombre: "MORRÓN VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.342, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 503,
    tipo: "almuerzo",
    principal: "CHORIZO A LA PORMAROLA CON PURE DE PAPA",
    postre: "QUESO Y DULCE",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHORIZO CRIOLLO", pb: 0.26, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.4, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE BATATA", pb: 0.025, unidad: "kg" },
      { nombre: "DULCE DE MEMBRILLO", pb: 0.025, unidad: "kg" },
      { nombre: "QUESO CREMOSO", pb: 0.05, unidad: "kg" },
    ],
  },
  {
    id: 504,
    tipo: "almuerzo",
    principal: "PATYNESA C/ ENSALADA",
    postre: "FRUTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "LECHUGA", pb: 0.08, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.12, unidad: "kg" },
      { nombre: "PATYNESA", pb: 1.0, unidad: "unidad" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 505,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "BUDIN DE PAN",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.04, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.04, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "HUEVOS", pb: 0.6, unidad: "unidad" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 506,
    tipo: "almuerzo",
    principal: "HAMBURGUESA C/ ENSALADA",
    postre: "FLAN CON CARAMELO",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "ALBAHACA", pb: 0.01, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO TAL", pb: 0.1, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.008, unidad: "kg" },
      { nombre: "HAMBURGUESA DE CARNE", pb: 2.0, unidad: "unidad" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 507,
    tipo: "almuerzo",
    principal: "RAVIOLES C/ ESTOFADO DE POLLO",
    postre: "FRUTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.2, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "RAVIOLES DE VERDURA", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 508,
    tipo: "cena",
    principal: "GUISO DE FIDEOS",
    postre: "FLAN",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO", pb: 0.09, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 509,
    tipo: "cena",
    principal: "PASTEL DE PAPAS",
    postre: "POSTRE DE VAINILLA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.25, unidad: "unidad" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.5, unidad: "kg" },
      { nombre: "PUERRO", pb: 0.005, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.18, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 510,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "FLAN CON DDL",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.1, unidad: "kg" },
      { nombre: "LENTEJA SECA", pb: 0.08, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.02, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE LECHE", pb: 0.01, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 511,
    tipo: "cena",
    principal: "POLENTA CON BOLOGÑESA",
    postre: "POSTRE",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.003, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "HARINA DE MAIZ", pb: 0.06, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.005, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.008, unidad: "kg" },
      { nombre: "RECORTE", pb: 0.064, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 512,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "CHUÑO",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "BATATA", pb: 0.03, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHOCLO EN GRANO", pb: 0.015, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.1, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.03, unidad: "kg" },
      { nombre: "PULPA DE JAMÓN", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "ALMIDÓN DE MAÍZ", pb: 0.015, unidad: "kg" },
      { nombre: "AZÚCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "litros" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.008, unidad: "kg" },
    ],
  },
  {
    id: 513,
    tipo: "cena",
    principal: "MONDONGO A LA BRETONA",
    postre: "COMPOTA MIXTA",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.02, unidad: "kg" },
      { nombre: "CHORIZO COLORADO", pb: 0.02, unidad: "kg" },
      { nombre: "GARBANZO", pb: 0.03, unidad: "kg" },
      { nombre: "MONDONGO", pb: 0.15, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PANCETA", pb: 0.02, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.1, unidad: "kg" },
      { nombre: "POROTO SECO", pb: 0.02, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.02, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.01, unidad: "kg" },
      { nombre: "CIRUELA DESHIDRATADA", pb: 0.03, unidad: "kg" },
      { nombre: "EDULCORANTE LÍQUIDO", pb: 0.005, unidad: "litros" },
      { nombre: "MANZANA ROJA C/D", pb: 0.12, unidad: "kg" },
    ],
  },
  {
    id: 514,
    tipo: "cena",
    principal: "PAN DE CARNE C/ ARROZ BLANCO",
    postre: "FLAN",
    regimen: "hiperproteico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "litros" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "MANTECA", pb: 0.005, unidad: "kg" },
      { nombre: "QUESO SARDO", pb: 0.01, unidad: "kg" },
      { nombre: "ACEITE DE GIRASOL (extra)", pb: 0.01, unidad: "litros" },
      { nombre: "CEBOLLA", pb: 0.025, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.3, unidad: "unidad" },
      { nombre: "PAN RALLADO", pb: 0.05, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 601,
    tipo: "almuerzo",
    principal: "ARROZ CON POLLO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/PURE MIXTO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "GUISO DE LENTEJAS",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "MILANESA DE CARNE COCIDA C/ENSALADA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "HAMBURGUESAS INDUSTR.CON PURE MIXTO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "POLLO AL HORNO C/ARROZ PRIMAVERA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "BANANA",
    regimen: "hiv",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "ALBONDIGAS CON SALSA Y PURE PURE DE PAPA Y BATATA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "ARROZ CON POLLO",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "FIDEOS TALLARIN CON ESTOFADO",
    postre: "MANDARINA",
    regimen: "hiv",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "NARANJA",
    regimen: "hiv",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "NARANJA",
    regimen: "hiv",
  },

  {
    id: 701,
    tipo: "almuerzo",
    principal: "ALBONDIGA CON PURE CALABAZA",
    postre: "GELATINA",
    regimen: "celiaco",
  },
  {
    id: 2,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON PANACHE DE VERDURA",
    postre: "FLAN DE VAINILLA",
    regimen: "celiaco",
  },
  {
    id: 3,
    tipo: "almuerzo",
    principal: "PASTEL DE CALABAZA DE CARNE",
    postre: "CHUÑO",
    regimen: "celiaco",
  },
  {
    id: 4,
    tipo: "almuerzo",
    principal: "HAMBURGUESA CASERA CON PURE DE CALABAZA",
    postre: "FLAN",
    regimen: "celiaco",
  },
  {
    id: 5,
    tipo: "almuerzo",
    principal: "ASADO CON ENSALADA",
    postre: "GELATINA",
    regimen: "celiaco",
  },
  {
    id: 6,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO CON ZANAHORIA Y CALABAZA",
    postre: "DURAZNO",
    regimen: "celiaco",
  },
  {
    id: 7,
    tipo: "almuerzo",
    principal: "HAMBURGUESA CASERA DE CARNE CON TORTILLA DE ACELGA",
    postre: "GELATINA",
    regimen: "celiaco",
  },
  {
    id: 8,
    tipo: "cena",
    principal: "FIDEO DE ARROZ CON ESTOFADO DE POLLO",
    postre: "MANZANA",
    regimen: "celiaco",
  },
  {
    id: 9,
    tipo: "cena",
    principal: "SALPICON DE POLLO",
    postre: "DURAZNO",
    regimen: "celiaco",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "CHURRASCO CON ENSALADA DE LECHUGA Y TOMATE",
    postre: "BANANA",
    regimen: "celiaco",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "PASTEL MIXTO DE CARNE",
    postre: "MANZANA",
    regimen: "celiaco",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "ALBONDIGA DE POLLO CON ACELGA GRATINADA",
    postre: "BANANA",
    regimen: "celiaco",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "FIDEO DE ARROZ CON BOLOGNESA",
    postre: "NARANJA",
    regimen: "celiaco",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "HAMBURGUESA DE POLLO CON ARROZ",
    postre: "BANANA",
    regimen: "celiaco",
  },

  {
    id: 801,
    tipo: "almuerzo",
    principal: "CARNE AL HORNO C/ PURE",
    postre: "GELATINA MERENGADA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.01, unidad: "kg" },
      { nombre: "PALETA SIN TAPA", pb: 0.168, unidad: "kg" },
      { nombre: "MARGARINA", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.44, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZÚCAR BLANCA", pb: 0.005, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.5, unidad: "unidad" },
      { nombre: "POLVO PARA PREPARAR GELATINA", pb: 0.025, unidad: "kg" },
    ],
  },
  {
    id: 802,
    tipo: "almuerzo",
    principal: "ARROZ C/ POLLO",
    postre: "FRUTA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "APIO", pb: 0.005, unidad: "kg" },
      { nombre: "ARROZ PARBOLIZADO", pb: 0.1, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.015, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.05, unidad: "kg" },
      { nombre: "CEBOLLA DE VERDEO", pb: 0.005, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.342, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.04, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 803,
    tipo: "almuerzo",
    principal: "CHORIZO A LA POMAROLA C/ PAPAS",
    postre: "FLAN C/ CARAMELO",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "CHORIZO CRIOLLO", pb: 0.26, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.4, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.05, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 804,
    tipo: "almuerzo",
    principal: "PATYNESA C/ ARROZ AMARILLO",
    postre: "FRUTA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ARROZ PARBOLIZADO", pb: 0.07, unidad: "kg" },
      { nombre: "ARVEJA SECA", pb: 0.02, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MANTECA", pb: 0.005, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PATYNESA", pb: 1.0, unidad: "kg" },
    ],
    postreIngredientes: [{ nombre: "FRUTA", pb: 0.18, unidad: "kg" }],
  },
  {
    id: 805,
    tipo: "almuerzo",
    principal: "ASADO C/ ENSALADA",
    postre: "BUDIN DE PAN",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "CEBOLLA", pb: 0.005, unidad: "kg" },
      { nombre: "CHORIZO BOMBON", pb: 0.06, unidad: "kg" },
      { nombre: "LECHUGA", pb: 0.07, unidad: "kg" },
      { nombre: "NARANJA", pb: 0.15, unidad: "kg" },
      { nombre: "ASADO", pb: 0.4, unidad: "kg" },
      { nombre: "TOMATE", pb: 0.06, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.04, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.7, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 806,
    tipo: "almuerzo",
    principal: "RAVIOLES C/ ESTOFADO DE POLLO",
    postre: "FLAN C/ CARAMELO",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "POLLO 10 CABEZAS", pb: 0.207, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.04, unidad: "kg" },
      { nombre: "RAVIOLES DE VERDURA", pb: 0.2, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.01, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "DULCE DE LECHE", pb: 0.01, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 807,
    tipo: "cena",
    principal: "GUISO DE FIDEOS",
    postre: "FLAN",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.01, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.03, unidad: "kg" },
      { nombre: "FIDEO SEMOLADO GUISERO", pb: 0.1, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.01, unidad: "kg" },
      { nombre: "PURE DE TOMATE", pb: 0.03, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.15, unidad: "kg" },
      { nombre: "ZANAHORIA", pb: 0.03, unidad: "kg" },
      { nombre: "ZAPALLO ANCO", pb: 0.03, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.02, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.02, unidad: "kg" },
    ],
  },
  {
    id: 808,
    tipo: "cena",
    principal: "PASTEL DE PAPAS",
    postre: "POSTRE DE VAINILLA",
    regimen: "hipercalorico",
    ingredientes: [
      { nombre: "ACEITE DE GIRASOL", pb: 0.005, unidad: "kg" },
      { nombre: "CEBOLLA", pb: 0.04, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.25, unidad: "kg" },
      { nombre: "MORRON VERDE", pb: 0.001, unidad: "kg" },
      { nombre: "PAPA BLANCA", pb: 0.5, unidad: "kg" },
      { nombre: "PUERRO", pb: 0.005, unidad: "kg" },
      { nombre: "ROAST BEEF", pb: 0.18, unidad: "kg" },
    ],
    postreIngredientes: [
      { nombre: "AZUCAR BLANCA", pb: 0.04, unidad: "kg" },
      { nombre: "ESENCIA DE VAINILLA", pb: 0.001, unidad: "kg" },
      { nombre: "HUEVOS", pb: 0.6, unidad: "kg" },
      { nombre: "LECHE ENTERA EN POLVO", pb: 0.013, unidad: "kg" },
      { nombre: "POLVO PARA PREPARAR FLAN", pb: 0.01, unidad: "kg" },
    ],
  },
  {
    id: 9,
    tipo: "cena",
    principal: "PASTEL DE PAPA",
    postre: "BUDIN DE PAN C/FLAN",
    regimen: "hipercalorico",
  },
  {
    id: 10,
    tipo: "cena",
    principal: "GUISO DE LENTEJAS",
    postre: "DURAZNO EN ALMIBAR",
    regimen: "hipercalorico",
  },
  {
    id: 11,
    tipo: "cena",
    principal: "POLENTA CON SALSA BOLOGNESA",
    postre: "POSTRE DE VAINILLA",
    regimen: "hipercalorico",
  },
  {
    id: 12,
    tipo: "cena",
    principal: "GUISO CARRERO",
    postre: "MANZANA",
    regimen: "hipercalorico",
  },
  {
    id: 13,
    tipo: "cena",
    principal: "MONDONGO A LA BRETONA",
    postre: "GELATINA MERENGADA",
    regimen: "hipercalorico",
  },
  {
    id: 14,
    tipo: "cena",
    principal: "PAN DE CARNE CON ARROZ BLANCO",
    postre: "BANANA",
    regimen: "hipercalorico",
  },
];
localStorage.setItem("comida", JSON.stringify(menus));
